[project]
name = "steamgamepath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prompt-toolkit>=3.0.51",
    "rich>=14.0.0",
    "vdf>=3.4",
]
