#!/bin/dash

if [ -z "$1" ]
  then
	if [ -z "$2" ]
         then 
		echo "input source html to extract albums and tracks: "
		read file
		echo "input artist name: "
		read artist
	   
        fi
fi


# File that contains the source html for the bandcamp page
file=$1

# artist
artist=$2

cat $file | grep "/track/" | sed -n 's/.*href="\([^"]*\).*/\1/p'| xargs -I var echo "https://$artist"".bandcamp.com"var > tracks.txt
cat $file | grep "/album/" | sed -n 's/.*href="\([^"]*\).*/\1/p'| xargs -I var echo "https://$artist""bandcamp.com"var > albums.txt
