#!/bin/dash

if [ -z "$1" ]
  then
	if [ -z "$2" ]
         then 
		echo "input source html to extract albums and tracks: "
		read file
		echo "input folder name to store results"
		read folder
		echo "input artist name: "
		read artist
	   
        fi
fi


# File that contains the source html for the bandcamp page
file=$1

# Folder to output the exported bandcamp and tracks list
folder=$2

# artist
artist=$3

mkdir $folder
# cd $folder

cat $file | grep "/track/" | sed -n 's/.*href="\([^"]*\).*/\1/p'| xargs -I var echo "$artist"".bandcamp.com"var > ./$folder/tracks.txt
cat $file | grep "/album/" | sed -n 's/.*href="\([^"]*\).*/\1/p'| xargs -I var echo "$artist"".bandcamp.com"var > ./$folder/albums.txt
