[project]
name = "bandcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bandcamp-downloader>=0.0.17",
    "beautifulsoup4>=4.13.4",
    "nicegui>=2.16.1",
]
